### ISSUE TITLE
Create Load Test Suite to test for population of the state at least 5% concurrency

### ISSUE THREAD

**Issue by aisegfault** [covid-alert-ny/covid-green-backend-api#10]
Create Load Test Suite potentially using locust.io to test for population of the state at least 5% concurrency
We can use the existing regression services collection

**Comment by mikegwhit** [comment]
Would apache bench be suitable for load testing?  I'm happy to pick this one up.  Does anyone recommend a different tool to use?

**Comment by aisegfault** [comment]
done with locust
