### ISSUE TITLE
Metrics upsert appears to be very expensive

### ISSUE THREAD

**Issue by erhudy** [covid-alert-ny/covid-green-backend-api#24]
In our load testing, the metrics upsert is by a couple orders of magnitude the most expensive database query. We tried to disable it via the SSM `enable_metrics` parameter and re-run our tests, but it appears that this parameter does not actually control all of the places where metrics are involved, because the upsert still happens. We would:

a) adjust this so that the parameter actually works - at present disabling it appears to stop the app from plumbing the metrics route, but other code in the backend API still just calls the metrics SQL insert directly
b) like to turn it off entirely and run our load tests without any metrics table inserts whatsoever
c) fix the metrics collection to not bury the database

CC: @segfault, @arybka777

**Comment by colmharte** [comment]
This has been removed and is now populated from a lambda function
